CFLAGS=-Wall -g

all: ex1 ex3 ex7 ex8 ex9 ex10 \
	ex11 ex12 ex13 ex14 ex15 \
	ex16
ex1: ex1.c
	cc ex1.c -o ex1 $(CFLAGS)
ex3: ex3.c
	cc ex3.c -o ex3 $(CFLAGS)
ex7: ex7.c
	cc ex7.c -o ex7 $(CFLAGS)
ex8: ex8.c
	cc ex8.c -o ex8 $(CFLAGS)
ex9: ex9.c
	cc ex9.c -o ex9 $(CFLAGS)
ex10: ex10.c
	cc ex10.c -o ex10 $(CFLAGS)
ex11: ex11.c
	cc ex11.c -o ex11 $(CFLAGS)
ex12: ex12.c
	cc ex12.c -o ex12 $(CFLAGS)
ex13: ex13.c
	cc ex13.c -o ex13 $(CFLAGS)
ex14: ex14.c
	cc ex14.c -o ex14 $(CFLAGS)
ex15: ex15.c
	cc ex15.c -o ex15 $(CFLAGS)
ex16: ex16.c
	cc ex16.c -o ex16 $(CFLAGS)
clean:
	rm -rf *.dSYM ex1 ex3 ex7 ex8 ex9 \
		ex10 ex11 ex12 ex13 ex14 ex15 \
		ex16
